### ISSUE TITLE
Paid

### ISSUE THREAD

**Issue by MrScott666** [RangeMachine/BTCPayGateway#3]
Everything is working for the BTCPay gateway but...the invoice is never marked as paid on the AdminCP, therefore the key is not issued using Single Use Key.

**Comment by MrScott666** [comment]
I am pretty sure I just need the webhook. Which you have left out.

**Comment by RangeMachine** [comment]
You dont need WebHook to mark transaction as paid. Check your IPN logs in BTCPayServer invoices.
