### ISSUE TITLE
Invalid access token

### ISSUE THREAD

**Issue by akaryoku** [RangeMachine/BTCPayGateway#4]
Hello, I'm running IPS 4.4 and I setup a store for BTCPay, I went over to access tokens and generated a key, however when I put that key into the Access Token area in the payment method setup got the gateway it keeps saying Invalid Access Token.

**Comment by RangeMachine** [comment]
Make sure you copy last "==" symbols, they dont get copied via ctrl-c ctrl-v some reason.

**Comment by akaryoku** [comment]
Did confirmed the "==" were at the end, but still have the Invalid Access Token message.

**Comment by RangeMachine** [comment]
Are you sure you using legacy token?

Theres code how it checks token: https://github.com/RangeMachine/BTCPayGateway/blob/0ba45698e406144962ff890f6108c2e1a34f170f/sources/sources/Gateway.php#L218

Make sure your sever can send that request.
