### ISSUE TITLE
Guest User permission

### ISSUE THREAD

**Issue by bulldawgXXX** [RangeMachine/BTCPayGateway#5]
When Guest User permission "Can access community?" is set to no, gateway stops working, because hook is not accessible?

Its possible to maken an order but paid/settled status is not pushed back to ipboard

**Comment by bulldawgXXX** [comment]
This is is what i see in my nginx log when the payment is settled:
[17/May/2022:01:59:08 +0000] "POST /index.php?/btcpay/transaction/37/ HTTP/1.1" 301 0 "-" "-"

When guest user permission have access to community, everthing runs fine. Payment status will pushed to ipforum after payment
[17/May/2022:01:39:18 +0000] "POST /index.php?/btcpay/transaction/37/ HTTP/1.1" 200 0 "-" "-"



So i think thats a permission issue? Is there a workaround for closed/non-guest accessible community?

**Comment by bulldawgXXX** [comment]
Any idea?

**Comment by RangeMachine** [comment]
Hello, sorry did not seen your issue, I will check it soon.

**Comment by RangeMachine** [comment]
Sadly seems its not possible to fix, because IPS devs require IPN being a controller, and that controller is not accessable without guest access.
![image](https://user-images.githubusercontent.com/11577601/177780401-5165a4a6-3d2e-4331-a035-f405227fc935.png)
