### ISSUE TITLE
Add/Mark this App Compatible with PHP8.0+/4.7 IPB

### ISSUE THREAD

**Issue by Wubzzz1337** [RangeMachine/BTCPayGateway#6]
As the title says.

Its working fine as it is, im just suggestion to add just the support "tags" so IPS things its correct etc :P

**Comment by RangeMachine** [comment]
Thank you for remind, I will do this as soon as possible.

**Comment by RangeMachine** [comment]
Done:
![image](https://user-images.githubusercontent.com/11577601/209243616-334d2a9f-6e18-45f4-875f-cf48ca756ff8.png)
