### ISSUE TITLE
Compatibility issue with Gateway Discounts

### ISSUE THREAD

**Issue by Rick7C2** [RangeMachine/BTCPayGateway#7]
When using BTCPayGateway along with [Gateway Discounts](https://invisioncommunity.com/files/file/10033-gateway-discounts/) there is an issue.

The Gateway Discounts settings will not populate in the BTCPayGateway settings page.

Below is a fix that will allow both addons to work together enabling the ability to give discounts to those who pay with crypto!

**Open the file:** /btcpay/sources/Gateway.php

**Find:**
`$this->settings( $form );`

**Add below:**
`parent::form( $form );`

**Comment by RangeMachine** [comment]
Thank you for your pull request, I will merge it as soon as possible.

**Comment by RangeMachine** [comment]
Merged with https://github.com/RangeMachine/BTCPayGateway/commit/780bd8cc72354020b906a8e10f18caf6aacf93e4, thank you for contribution.
